#!/usr/bin/env python3
"""Summarize read-only Unitree LowState hip/knee torque logs."""

from __future__ import annotations

# Support direct execution as well as python -m from the project root.
if __package__ in (None, ""):
    import sys as _sys
    from pathlib import Path as _Path
    _sys.path.insert(0, str(_Path(__file__).resolve().parents[2]))


import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def parse_window(value: Optional[str]) -> Optional[Tuple[float, float]]:
    if not value:
        return None
    parts = [p.strip() for p in value.split(",")]
    if len(parts) != 2:
        raise argparse.ArgumentTypeError("window must be START,END in seconds")
    start, end = float(parts[0]), float(parts[1])
    if not math.isfinite(start) or not math.isfinite(end) or end <= start:
        raise argparse.ArgumentTypeError("window must satisfy END > START")
    return start, end


def in_window(t: float, window: Optional[Tuple[float, float]]) -> bool:
    return window is None or (window[0] <= t <= window[1])


def summarize(rows: List[Dict[str, str]], window: Optional[Tuple[float, float]], label: str) -> List[Dict[str, object]]:
    grouped: Dict[int, List[Dict[str, str]]] = defaultdict(list)
    for row in rows:
        t = float(row["t_rel_s"])
        if in_window(t, window):
            grouped[int(row["joint_id"])].append(row)

    out: List[Dict[str, object]] = []
    for joint_id, items in sorted(grouped.items()):
        taus = [float(r["tau_est"]) for r in items]
        times = [float(r["t_rel_s"]) for r in items]
        if not taus:
            continue
        peak_index = max(range(len(taus)), key=lambda i: abs(taus[i]))
        duration = max(times) - min(times) if len(times) > 1 else 0.0
        out.append(
            {
                "window": label,
                "joint_id": joint_id,
                "joint_name": items[0].get("joint_name", f"joint_{joint_id}"),
                "samples": len(taus),
                "duration_s": duration,
                "tau_abs_peak_nm": abs(taus[peak_index]),
                "tau_peak_signed_nm": taus[peak_index],
                "tau_peak_t_rel_s": times[peak_index],
                "tau_rms_nm": math.sqrt(sum(t * t for t in taus) / len(taus)),
                "tau_mean_abs_nm": sum(abs(t) for t in taus) / len(taus),
            }
        )
    return out


def read_rows(path: Path) -> List[Dict[str, str]]:
    with path.open("r", newline="") as f:
        return list(csv.DictReader(f))


def write_summary(path: Path, rows: List[Dict[str, object]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = list(rows[0].keys())
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def print_summary(rows: List[Dict[str, object]]) -> None:
    if not rows:
        print("No samples in the requested windows.")
        return
    for row in rows:
        print(
            f"{row['window']:>8}  joint {row['joint_id']} {row['joint_name']}: "
            f"peak={row['tau_peak_signed_nm']:.3f} Nm at t={row['tau_peak_t_rel_s']:.3f}s, "
            f"abs_peak={row['tau_abs_peak_nm']:.3f} Nm, rms={row['tau_rms_nm']:.3f} Nm"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path, help="CSV generated by h1_torque_logger")
    parser.add_argument("--landing-window", type=parse_window, help="Landing impact window: START,END seconds")
    parser.add_argument("--walking-window", type=parse_window, help="Walking torque window: START,END seconds")
    parser.add_argument("--out", type=Path, help="Optional summary CSV path")
    args = parser.parse_args()

    rows = read_rows(args.csv)
    summaries: List[Dict[str, object]] = []
    summaries.extend(summarize(rows, args.landing_window, "landing" if args.landing_window else "all"))
    if args.walking_window:
        summaries.extend(summarize(rows, args.walking_window, "walking"))

    print_summary(summaries)
    if args.out:
        write_summary(args.out, summaries)
        print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
